### ISSUE TITLE
"enhanced", higher contrast color palette on heatmap

### ISSUE THREAD

**Issue by spiermar** [Netflix/flamescope#4]

**Comment by brendangregg** [comment]
It would be great to have an "Enhance" button that switched to a palette like this, based on count:

- 0: white
- 1-2: shades of blue (light->dark).
- 3-max: a red scale (pink->red?)

The aim is to highlight single-threaded activity, which will either have a count of 1 (eg, 49 Hertz sampling on a 50 row heatmap) or 2 (99 Hertz sampling on a 50 row heatmap). Hence making 1 & 2 blue, and the rest shades of red.

Here is an example. This is application startup, which includes many single-threaded stages. Since they have low counts in the columns, they are almost white in the default profile.

![screen shot 2018-04-04 at 11 46 08 am](https://user-images.githubusercontent.com/1101211/38327975-8002126e-37fe-11e8-8f5f-076017caadf3.png)

Imagine an "Enhance" button that then switched to the low-count highlighting palette:

![screen shot 2018-04-04 at 11 50 19 am](https://user-images.githubusercontent.com/1101211/38327997-8b9c439c-37fe-11e8-9d9c-798f64121c7c.png)

That looks ok (the blue goes beyond a 1-2 count in this mock up, which it shouldn't). I'd resist adding more colors to this (think weather radar maps) since it can become visually ugly. Keep it simple. Blue, then a red scale.

This should be easy to do. See the colorScale() function in the heat map.

**Comment by ceeaspb** [comment]
We also get feint colors; I wanted to explore the single color.

<img width="411" alt="screen shot 2018-04-09 at 18 26 05" src="https://user-images.githubusercontent.com/7397675/38512693-d33c3cc4-3c23-11e8-9f14-66f716382e31.png">

<img width="408" alt="screen shot 2018-04-09 at 18 26 49" src="https://user-images.githubusercontent.com/7397675/38512704-dd64941c-3c23-11e8-85d4-d83e8f28fba3.png">

<img width="414" alt="screen shot 2018-04-09 at 18 30 23" src="https://user-images.githubusercontent.com/7397675/38512793-1dd11bb0-3c24-11e8-975c-1761082a56a4.png">

**Comment by spiermar** [comment]
@brendangregg assuming this is closed.

**Comment by brendangregg** [comment]
@ceeaspb that's a pretty interesting profile. How does it look with the new "Enhance Colors" button? Maybe so interesting it deserves a blog post. :)

**Comment by ceeaspb** [comment]
@brendangregg sorry combination of holiday and been busy - I wasn't sure at first but yes it looks great with the enhanced palette! And yes I need to work on my blog writing skills :)
The handful of really intense cpu activity pixels was perf itself, which I should probably ask about on perf-users.
